version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - 8083:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: taskmanagementdb