version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'taskmanagementdb'  
      MYSQL_USER: 'rt'                    
      MYSQL_PASSWORD: '123Tommy!@#'     
      MYSQL_ROOT_PASSWORD: '123Tommy!@#'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
